package org.opensources.pokmaps.ui.map

/** Nom français des personnages et éléments de décor, d'après leur sprite (identifiants des désassemblages pret). */
private val NPC_NAMES = mapOf(
    "balding-guy" to "Monsieur",
    "beauty" to "Canon",
    "bike-shop-clerk" to "Vendeur de vélos",
    "bird" to "Pokémon oiseau",
    "blue" to "Rival",
    "boulder" to "Rocher",
    "brunette-girl" to "Jeune femme",
    "bulbasaur" to "Bulbizarre",
    "captain" to "Capitaine",
    "channeler" to "Exorciste",
    "chansey" to "Leveinard",
    "clefairy" to "Mélofée",
    "clerk" to "Vendeur",
    "clipboard" to "Bloc-notes",
    "cook" to "Cuisinier",
    "cooltrainer-f" to "Topdresseuse",
    "cooltrainer-m" to "Topdresseur",
    "daisy" to "Sœur du rival",
    "fairy" to "Pokémon",
    "fisher" to "Pêcheur",
    "fishing-guru" to "Maître pêcheur",
    "fossil" to "Fossile",
    "gambler" to "Parieur",
    "gambler-asleep" to "Parieur endormi",
    "gameboy-kid" to "Enfant",
    "gentleman" to "Gentleman",
    "girl" to "Fille",
    "gramps" to "Vieil homme",
    "granny" to "Vieille dame",
    "guard" to "Garde",
    "gym-guide" to "Guide de l'arène",
    "hiker" to "Montagnard",
    "james" to "James",
    "jessie" to "Jessie",
    "jigglypuff" to "Rondoudou",
    "link-receptionist" to "Hôtesse du Club Link",
    "little-boy" to "Petit garçon",
    "little-girl" to "Petite fille",
    "middle-aged-man" to "Homme",
    "middle-aged-woman" to "Femme",
    "mom" to "Maman",
    "monster" to "Pokémon",
    "mr-fuji" to "M. Fuji",
    "nurse" to "Infirmière",
    "oak" to "Prof. Chen",
    "oddish" to "Mystherbe",
    "officer-jenny" to "Agent Jenny",
    "old-amber" to "Vieil Ambre",
    "paper" to "Papier",
    "pikachu" to "Pikachu",
    "poke-ball" to "Poké Ball",
    "pokedex" to "Pokédex",
    "rocker" to "Rockeur",
    "rocket" to "Sbire Rocket",
    "safari-zone-worker" to "Employé du Parc Safari",
    "sailor" to "Marin",
    "sandshrew" to "Sabelette",
    "scientist" to "Scientifique",
    "seel" to "Otaria",
    "silph-president" to "Président de Sylphe SARL",
    "silph-worker-f" to "Employée de Sylphe SARL",
    "silph-worker-m" to "Employé de Sylphe SARL",
    "snorlax" to "Ronflex",
    "super-nerd" to "Intello",
    "swimmer" to "Nageur",
    "waiter" to "Serveur",
    "warden" to "Gardien du Parc Safari",
    "youngster" to "Gamin"
)

fun npcName(sprite: String?): String = sprite?.let { NPC_NAMES[it] } ?: "Personnage"
